# This is a basic workflow to help you get started with Actions

name: my-basics
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: action/setup-node@v1
    - name: test start
      run: npm test
    - name: npm install
      run: make install
    - name: Run test
      run: npm test 

